In [1]:
import numpy as np
import torch.nn.functional as F
import torchvision.transforms as transforms

# 1. Train Same Tensor

### 1. Load image

In [2]:
input_img = np.zeros((2, 2), dtype=np.uint8)
print(input_img)
print(input_img.shape)

[[0 0]
 [0 0]]
(2, 2)


In [3]:
target_img = np.full((2, 2), 255, dtype=np.uint8)
print(target_img)
print(target_img.shape)

[[255 255]
 [255 255]]
(2, 2)


### 1.2 Transform to tensor

In [4]:
transform = transforms.Compose([
    transforms.ToTensor(),
])

In [5]:
input_tensor = transform(input_img)
print(input_tensor)
print(input_tensor.shape)

tensor([[[0., 0.],
         [0., 0.]]])
torch.Size([1, 2, 2])


In [6]:
target_tensor = transform(target_img)
print(target_tensor)
print(target_tensor.shape)

tensor([[[1., 1.],
         [1., 1.]]])
torch.Size([1, 2, 2])


### 1.3 Calculate loss

<img src="./notebook_images/mse_loss.jpg">

In [7]:
mse_loss = F.mse_loss(input_tensor, target_tensor)
print(mse_loss)

tensor(1.)


### 1.4 Calculate gradient

<img src="./notebook_images/mse_loss_gradient.jpg">

In [8]:
gradient = 1 * 2 * (input_tensor - target_tensor)
print(gradient)

tensor([[[-2., -2.],
         [-2., -2.]]])


### 1.5 Update input_tensor (SGD)

<img src="./notebook_images/mse_loss_update.jpg">

In [9]:
new_input_tensor = input_tensor - (0.001 * gradient)
print(new_input_tensor)

tensor([[[0.0020, 0.0020],
         [0.0020, 0.0020]]])


In [10]:
epochs = 10
before_input_tensor = input_tensor.clone()
for epoch in range(epochs):
    mse_loss = F.mse_loss(input_tensor, target_tensor)

    gradient = 1 * 2 * (input_tensor - target_tensor)
    input_tensor = input_tensor - (0.2 * gradient)
    
    print(f"{epoch+1}/{epochs}: loss: {mse_loss:.4f}")

print(f"input_tensor: \n{before_input_tensor}\n")
print(f"target_tensor: \n{target_tensor}\n")
print(f"Updated input_tensor: \n{input_tensor}\n")

1/10: loss: 1.0000
2/10: loss: 0.3600
3/10: loss: 0.1296
4/10: loss: 0.0467
5/10: loss: 0.0168
6/10: loss: 0.0060
7/10: loss: 0.0022
8/10: loss: 0.0008
9/10: loss: 0.0003
10/10: loss: 0.0001
input_tensor: 
tensor([[[0., 0.],
         [0., 0.]]])

target_tensor: 
tensor([[[1., 1.],
         [1., 1.]]])

Updated input_tensor: 
tensor([[[0.9940, 0.9940],
         [0.9940, 0.9940]]])



# 2. Train Diff Tensor

### 2.1 Load image

In [11]:
input_img = np.zeros((2, 2), dtype=np.uint8)
print(input_img)
print(input_img.shape)

[[0 0]
 [0 0]]
(2, 2)


In [12]:
target_img = np.array([[50, 50], [50, 200]], dtype=np.uint8)
print(target_img)
print(target_img.shape)

[[ 50  50]
 [ 50 200]]
(2, 2)


### 2.2 Transform to tensor

In [13]:
transform = transforms.Compose([
    transforms.ToTensor(),
])

In [14]:
input_tensor = transform(input_img)
print(input_tensor)
print(input_tensor.shape)

tensor([[[0., 0.],
         [0., 0.]]])
torch.Size([1, 2, 2])


In [15]:
target_tensor = transform(target_img)
print(target_tensor)
print(target_tensor.shape)

tensor([[[0.1961, 0.1961],
         [0.1961, 0.7843]]])
torch.Size([1, 2, 2])


### 2.3 Calculate loss

<img src="./notebook_images/mse_loss.jpg">

In [16]:
mse_loss = F.mse_loss(input_tensor, target_tensor)
print(mse_loss)

tensor(0.1826)


### 2.4 Calculate gradient

<img src="./notebook_images/mse_loss_gradient.jpg">

In [17]:
gradient = 1 * 2 * (input_tensor - target_tensor)
print(gradient)

tensor([[[-0.3922, -0.3922],
         [-0.3922, -1.5686]]])


### 2.5 Update input_tensor (SGD)

<img src="./notebook_images/mse_loss_update.jpg">

In [18]:
new_input_tensor = input_tensor - (0.001 * gradient)
print(new_input_tensor)

tensor([[[0.0004, 0.0004],
         [0.0004, 0.0016]]])


In [19]:
epochs = 10
before_input_tensor = input_tensor.clone()
for epoch in range(epochs):
    mse_loss = F.mse_loss(input_tensor, target_tensor)

    gradient = 1 * 2 * (input_tensor - target_tensor)
    input_tensor = input_tensor - (0.2 * gradient)
    
    print(f"{epoch+1}/{epochs}: loss: {mse_loss:.4f}")

print(f"input_tensor: \n{before_input_tensor}\n")
print(f"target_tensor: \n{target_tensor}\n")
print(f"Updated input_tensor: \n{input_tensor}\n")

1/10: loss: 0.1826
2/10: loss: 0.0657
3/10: loss: 0.0237
4/10: loss: 0.0085
5/10: loss: 0.0031
6/10: loss: 0.0011
7/10: loss: 0.0004
8/10: loss: 0.0001
9/10: loss: 0.0001
10/10: loss: 0.0000
input_tensor: 
tensor([[[0., 0.],
         [0., 0.]]])

target_tensor: 
tensor([[[0.1961, 0.1961],
         [0.1961, 0.7843]]])

Updated input_tensor: 
tensor([[[0.1949, 0.1949],
         [0.1949, 0.7796]]])

